baseURL = "/"
languageCode = "en-us"
title = "Ongiza"
theme = "hugo-hero-theme"


[params]
    google_analytics_id=""

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
